name: guarda_corpo_2024
description: "A new Flutter project."

publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  permission_handler: ^12.0.1
  url_launcher: ^6.3.2
  flutter_phone_direct_caller: ^2.0.0
  syncfusion_flutter_pdfviewer: ^31.1.19
  google_mobile_ads: ^6.0.0
  webview_flutter: ^4.9.0
  webview_flutter_android: any
  webview_flutter_wkwebview: any
  upgrader: ^12.0.0
  shared_preferences: ^2.3.3
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  introduction_screen: ^4.0.0
  in_app_update: ^4.2.5
  flutter_speed_dial: ^7.0.0
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  logger: ^2.5.0
  cloud_firestore: ^6.0.0
  firebase_messaging: ^16.0.0
  in_app_purchase: ^3.2.1
  package_info_plus: ^9.0.0
  http: ^1.3.0
  html: ^0.15.4
  in_app_review: ^2.0.11
  flutter_local_notifications: ^19.5.0
  dtd: ^4.0.0
  flutter_lints: ^6.0.0
  google_fonts: ^6.3.3
  json_rpc_2: ^4.0.0
  path: ^1.9.1
  stack_trace: ^1.12.1
  web: ^1.1.1
  google_nav_bar: ^5.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/pdf_nr/
    - assets/nho/

  fonts:
    - family: Segoe
      fonts:
        - asset: assets/fonts/segoeresgular.ttf
    - family: Segoe Bold
      fonts:
        - asset: assets/fonts/segoebold.ttf
    - family: Segoe Black
      fonts:
        - asset: assets/fonts/segoeblack.ttf
    - family: Segoe Light
      fonts:
        - asset: assets/fonts/segoelight.ttf

